name: noteworthy
description: "A clean and accurate chromatic tuner."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  buffered_list_stream: ^1.3.0
  easy_rich_text: ^2.1.0
  flutter:
    sdk: flutter

  go_router: ^14.2.7
  pitch_detector_dart: ^0.0.7
  record: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true